.TH "Bone.h" 3 "Wed Jul 22 2020" "Version v0.1" "Lei2020" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bone.h \- Header for \fBBone\fP class is the definition of a bone for the skeleton\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for \fBBone\fP class is the definition of a bone for the skeleton\&. 


.PP
\fBAuthor\fP
.RS 4
Paulo Barbosa, Francisco Lira and Joel Gama 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2020-07-20
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Lei2020 from the source code\&.
